---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: csso-signing-task
spec:
  params:
    - name: api-key
    - name: vault-instance
    - name: key-name
    - name: region
    - name: resource-group
    - name: registry-region
    - name: registry-namespace
    - name: image-name
  steps:
    - name: sign-image
      image: huayuenh/csso_client:latest
      env:
        - name: IBM_CLOUD_API_KEY
          value: $(params.api-key)
        - name: VAULT_INSTANCE
          value: $(params.vault-instance)
        - name: KEY_NAME
          value: $(params.key-name)
        - name: IBMCLOUD_TARGET_REGION
          value: $(params.region)
        - name: RESOURCE_GROUP
          value: $(params.resource-group)
        - name: REGISTRY_REGION
          value: $(params.registry-region)
        - name: REGISTRY_NAMESPACE
          value: $(params.registry-namespace)
        - name: IMAGE_NAME
          value: $(params.image-name)
        - name: REGION
          value: $(params.region)
      script: |
          #!/bin/bash
          source /artifacts/build.properties
          IMAGE_TAG=$IMAGE_TAGS
          source <(curl -sSL "https://raw.githubusercontent.com/huayuenh/csso-image-signed-kube-toolchain/master/csso-signing-setup.sh")
          #Note - signing can be done performed using a single skopeo command
          #echo "PULL IMAGE"
          #skopeo copy docker://${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} dir:${SIGNING_DIR} --src-creds iamapikey:${IBM_CLOUD_API_KEY}
          #echo "BEGIN SIGNING PUSH TO REPO"
          #skopeo copy dir:${SIGNING_DIR} docker://${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} --dest-creds iamapikey:${IBM_CLOUD_API_KEY}  --sign-by ${SIGNING_KEY}
          echo "DIRECT REPO SIGNING"
          skopeo copy docker://${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} docker://${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG} --dest-creds iamapikey:${IBM_CLOUD_API_KEY} --src-creds iamapikey:${IBM_CLOUD_API_KEY} --sign-by ${SIGNING_KEY}
  workspaces:
    - name: artifacts
      description: A workspace backing by a volume
      mountPath: /artifacts